"""
GitHub 代码爬虫配置文件
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ============================================================================
# GitHub API配置
# ============================================================================

# 从token.json文件加载tokens
def load_tokens_from_file(token_file='token.json'):
    """从JSON文件加载GitHub tokens"""
    # 获取当前文件所在目录
    current_dir = os.path.dirname(os.path.abspath(__file__))
    token_path = os.path.join(current_dir, token_file)

    if os.path.exists(token_path):
        try:
            with open(token_path, 'r', encoding='utf-8') as f:
                tokens = json.load(f)
            print(f"✓ 从 {token_file} 加载了 {len(tokens)} 个tokens")
            return tokens
        except Exception as e:
            print(f"✗ 加载token文件失败: {e}")
            return []
    else:
        print(f"⚠️  未找到token文件: {token_path}")
        return []

# 加载tokens
GITHUB_TOKENS = load_tokens_from_file('token.json')

# 如果token.json不存在或为空，使用备用tokens
if not GITHUB_TOKENS:
    print("⚠️  使用config.py中的备用tokens")
    GITHUB_TOKENS = []

# GitHub API基础配置
GITHUB_API_BASE = "https://api.github.com"

# ============================================================================
# 爬取参数与限制
# ============================================================================

TARGET_TOTAL_FUNCTIONS = 4000        # 爬取函数总数上限（达到后停止）
MAX_RESULTS_PER_QUERY = 50         # 每次查询最多结果数（GitHub 限制 100）
MAX_FUNCTIONS_PER_API = 20          # 每个 API 最多保留的函数数
MAX_FUNCTIONS_PER_REPO = 5           # 每个仓库最多保留的函数数，提高多样性
MIN_QUALITY_SCORE = 60.0             # 最低质量门槛
API_WORKERS = 2                      # 并发处理 API 数量；保守并发降低 429 风险

# 速率限制配置
RATE_LIMIT_DELAY = 8.0              # 搜索请求后的轻量等待；请求会轮换token
QUERY_DELAY = 5.0                 # 查询层间隔（秒）
API_DELAY = 5.0                     # API切换间隔（秒）

# ============================================================================
# 注释优先策略
# ============================================================================

# 注释加分权重
COMMENT_BONUS_PER_LINE = 2.0        # 每行注释加2分
MAX_COMMENT_BONUS = 15.0            # 注释最多加15分
DOCSTRING_BONUS = 10.0              # 有docstring加10分

# 优先爬取有注释的代码
PRIORITIZE_COMMENTED_CODE = True    # 是否优先选择有注释的代码
MIN_COMMENT_LINES = 0               # 最少注释行数（0表示不强制）

# ============================================================================
# 仓库黑名单 - 排除工具生成项目
# ============================================================================

BLACKLIST_REPOS = {
    # 已知的工具生成项目
    'holi-lab/ToolDial',
    'Junjie-Ye/ToolEyes',
    'Sankar16/agentic-conversation-generator',
    'manishhnnegi/SmartBuddy',
    'Tech-Academy-Live-Project/Appbuilder9000',

    # 可以继续添加
}

# ============================================================================
# 自动生成代码检测模式
# ============================================================================

AUTO_GEN_PATTERNS = [
    # 工具名称
    'toolbench_rapidapi_key',
    'ToolBench',
    'ToolDial',
    'ToolEyes',

    # 生成标记
    'auto-generated',
    'automatically generated',
    'generated by',
    'code generator',
    'This code was generated',
    'Auto-generated code',

    # 模板变量模式（正则）
    r'var\d{2,}',      # var01, var02, ...
    r'temp\d{2,}',     # temp01, temp02, ...
    r'result\d{2,}',   # result01, result02, ...
    r'param\d{2,}',    # param01, param02, ...
]

# 代码相似度阈值
CODE_SIMILARITY_THRESHOLD = 0.85    # 85%相似度视为重复

# ============================================================================
# 查询策略 - 多层次搜索
# ============================================================================

QUERY_STRATEGIES = [
    'endpoint_url_match',        # Layer 0: RapidAPI文档完整endpoint URL精确匹配
    'endpoint_route_host_match', # Layer 0: 文档route + API host联合匹配
    'host_match',                # Layer 1: API host精确匹配
    'header_match',              # Layer 2: RapidAPI header匹配
    'library_match',             # Layer 3: 域名 + requests
    'function_match',            # Layer 4: 域名 + 函数定义
    'error_handling_match',      # Layer 5: 带错误处理的代码
    'keyword_match',             # Layer 6: API关键词 + rapidapi（兜底）
    'keyword_requests_match',    # Layer 7: 关键词 + requests方法（兜底）
]

# ============================================================================
# v3.1 加速配置
# ============================================================================

# 宽泛关键词查询只作为兜底；精确 host/header/library/function/error 查询找到候选后不再跑宽泛查询。
BROAD_QUERY_LAYERS = {'keyword_match', 'keyword_requests_match'}
RUN_BROAD_QUERIES_ONLY_AS_FALLBACK = True
MAX_BROAD_RESULTS_PER_QUERY = 15

# endpoint优先查询：提升“代码函数 ↔ RapidAPI文档endpoint”的强映射比例。
# 这里刻意只查每个API前2个endpoint，避免GitHub Search触发429。
ENDPOINT_QUERY_LAYERS = {'endpoint_url_match', 'endpoint_route_host_match'}
MAX_ENDPOINTS_PER_API_FOR_QUERIES = 2
MAX_ENDPOINT_RESULTS_PER_QUERY = 15
MIN_ENDPOINT_ROUTE_LENGTH = 4

# 这些关键词过于宽泛，命中大量无关代码时直接跳过宽泛查询。
GENERIC_BROAD_KEYWORDS = {
    'api', 'data', 'live', 'free', 'real', 'all', 'new', 'the',
    'best', 'world', 'college'
}

# 早期过滤：文件内容不包含目标 RapidAPI host 时，后续 AST/质量/repo 请求都跳过。
REQUIRE_HOST_IN_FILE = True

# 精确查询已经凑够候选函数时，跳过后续查询层，减少重复搜索请求。
STOP_QUERY_WHEN_ENOUGH_CANDIDATES = True
MIN_CANDIDATES_TO_STOP_QUERY = 20

# 进度文件只保存完成 API 列表，结果另存 JSONL，避免进度文件越来越大。
SAVE_FULL_RESULTS_IN_PROGRESS = False
JSONL_OUTPUT = os.path.join(BASE_DIR, 'crawled_data', 'all_functions.jsonl')

# ============================================================================
# 质量评分系统 v3.0
# ============================================================================

QUALITY_SCORING = {
    'syntax_valid': 30,         # 语法有效
    'has_api_call': 25,         # 有API调用
    'has_response_handling': 20, # 有响应处理
    'has_error_handling': 10,   # 有错误处理
    'code_length': 10,          # 代码长度合理
    'repo_quality': 5,          # 仓库质量
    'has_comments': 15,         # 有注释（新增）
    'has_docstring': 10,        # 有docstring（新增）
}

# 扣分项
QUALITY_PENALTIES = {
    'has_database_call': -30,   # 数据库调用
    'has_indentation_issue': -20, # 缩进问题
    'missing_imports': -10,     # 缺少导入
}

# ============================================================================
# 输出配置
# ============================================================================

OUTPUT_DIR = os.path.join(BASE_DIR, "crawled_data")
PROGRESS_FILE = os.path.join(BASE_DIR, "crawled_data", ".progress_v3.json")
FINAL_OUTPUT = os.path.join(BASE_DIR, "crawled_data", "all_functions_v3.json")

# ============================================================================
# RapidAPI元数据路径
# ============================================================================

RAPIDAPI_METADATA_DIR = os.path.join(BASE_DIR, "rapidapi_metadata", "by_category")

# ============================================================================
# 日志配置
# ============================================================================

LOG_LEVEL = "INFO"
LOG_FILE = os.path.join(BASE_DIR, "crawled_data", "crawler_v3.log")

# ============================================================================
# 多线程配置
# ============================================================================

NUM_THREADS = 20                        # 并发线程数
PROGRESS_REFRESH_INTERVAL = 120           # 进度刷新间隔（秒）
DATA_FLUSH_INTERVAL = 1                 # 数据落盘间隔（每N个函数）
MAX_RETRIES = 3                         # 失败重试次数
THREAD_PROGRESS_DIR = os.path.join(BASE_DIR, "crawled_data", "thread_progress")
MASTER_PROGRESS_FILE = os.path.join(BASE_DIR, "crawled_data", ".progress_master.json")
